apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY1QrV2lYNkZRK3N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMU1qSXhOVFE1TVRCYUZ3MHpOREExTWpBeE5UVTBNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR5Y2I5YkpibVBlb0xWcllDRmFmNGVSckdtZlpSaVF3THVpZ1RhbS9wWDlEdVMzdU5Xc01aYjJCbGgKcC9rdUFyMXhKOUhnRkJ3cFdkUS9oSityYXMvSW5pK2U3RU9YajcxM2JVcEpnTzFRNkN2QTUxUzlQM2syNGR3awpIR2RGOHJyQ0FycWhPZ1ZaaTc1ZEZ0K0pvNFVxNUFZSzBVZmRaR0dBTkdzWTcyTFY3TTdPNXRCRG5oM1dXbkN3ClNFTSsvblVoZ0h5S0ExS2paSTZWejAzUHY2RjhhdjJ6TUU5SDNiZ0F6NmFETnZZUy9qQlhMemdOUjhkeENWQlYKbTRIaVRRQU9uWlZDeVNqc3dLYWEvMTF0d2dXUVk2Z2lJVXlZNHgwaDJmZ1pMUXlJYjlzL2VONG5mWFBxSy9YYQpaZW5RVHIzTWVjZlF4cE95K3VuZi85VmRRRXJ4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNXh0WTlqamdGVU12Umk4MUdVQlZTdVcrM3hqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3BZVkxDQlIxagpsSmZKT3NNTmVDTDRCR1JaZTBBbWQweFBlU1VoNGY4NEVVeDBPdEtRZHN0dWQ1NU03TzJma3NwUUs0M0NnSnNjClE0MkV4Z0d0c2pSQ3JONlZTamtiN0RlMmVrdURkWEhlOGJQOEVuNlZvOGhPaktPeGJNb3J6c0wvN3JLNkhTcUwKaXE5a1BMSEhWbnJ5RlJNQlorVG5zd2lmeklzdjFnQmpQMWM5T3JGWDhsdEh6bDd3VDhBWnVJNERZN01XeCtHSgpKZWdYZGF2UHpqZXh3R0FwY0ZLaFV6M1NlamM1Qi9xRVFiZWpYMnFTaXBMZG5wWG5uZEdwTXRaVTFhQ2VrRUhICmRMZlVsWHBjaXRmVVFrbFlpZXFmYjlndDd4eklYTDB4S0hSNjVFR1J4blNoTHE4Unh0RjZTajNWeUg2bkZjVXAKQ1BBUllna1FWRFBQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://05559b21-0d5d-43cf-8941-170ec0dcb14b.eu-central-1.linodelke.net:443
  name: lke182387

users:
- name: lke182387-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImlVbk5pVE5SWkFzWlcyMmtaWk1OUDV4cmhXc0VfRWMzbVoyZUNfTEtCSUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tazI1dHoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTFiNjQ2ZDctZWUxMS00MDNjLWE4NWEtMTRiMmZhZDY4NWRlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.aiqcPJQ-PovbNO5DI9mepA0x-aX93z76fHwDElUkihV0h8RubwED_Rv_1O1YMErn675OB0LHzJaaI92IoAxxZn8v42crzOV76ECpFNpbsYRKs0Q5MAt4NtBExz-kS-_RqmAP2dwwevj0tMkvlQL9dIQB3kLNoIfdnIOMNrFtzQtwf5YZLTK7hRrlHmcPFxaym9Yh8LfLq4ydQxpGMaikiSn08cJH2Tdy__BC9h7PCRd7-q6EfYEjtyiBHsSE0s5t-IaTKXjtg3VWycaMFhsguatWWb1SnKr_GWXojR98c7Dd9eYjPg_DSm0T3PLPH61OhRXTFCxIRcy6PBnFPMT4Qg

contexts:
- context:
    cluster: lke182387
    namespace: default
    user: lke182387-admin
  name: lke182387-ctx

current-context: lke182387-ctx