apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/coino/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 24 May 2024 20:52:21 +03
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://127.0.0.1:64455
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 24 May 2024 20:52:21 +03
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/coino/.minikube/profiles/minikube/client.crt
    client-key: /Users/coino/.minikube/profiles/minikube/client.key
